config/routes.rb
Rails.application.routes.draw do
	resources :photos, only: [:new, :create, :index, :destroy]

  root 'static_pages#home'

  get '/about', to: 'static_pages#about', as: :about
  get '/contact', to: 'static_pages#contact', as: :contact
  get '/index', to: 'photos#index', as: :index
  
  get 'static_pages/about'
  get 'static_pages/contact'

end

 

app/models/photo.rb
class Photo < ActiveRecord::Base
	has_attached_file :image
	validates_attachment :image,
                       content_type: { content_type: ["image/jpeg", "image/gif", "image/png"] }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
	def index
		@photos = Photo.order('created_at')
	end

	def new
		@photo = Photo.new
	end

	def create
		@photo = Photo.new(photo_params)

		if @photo.save
			flash[:success] = "Your photo has been added! Good job!"
			redirect_to root_path
		else
			render :new
		end
	end

	private

	def photo_params
		params.require(:photo).permit(:image, :title)
	end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end

  def about
  end

  def contact  	
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
	# Returns the full title on a per-page basis.
  def full_title(page_title = '')
    base_title = "Nancy's Nails & Hair"
    if page_title.empty?
      base_title
    else
      "#{page_title} | #{base_title}"
    end
  end
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/_jobform.html.erb
<form>
  <div class="form-group">
    <label for="exampleInputEmail1">Email address</label>
    <input type="email" class="form-control" id="exampleInputEmail1" placeholder="Email">
  </div>
  <div class="form-group">
    <label for="exampleInputPassword1">Password</label>
    <input type="password" class="form-control" id="exampleInputPassword1" placeholder="Password">
  </div>
  <div class="form-group">
    <label for="exampleInputFile">File input</label>
    <input type="file" id="exampleInputFile">
    <p class="help-block">Example block-level help text here.</p>
  </div>
  <div class="checkbox">
    <label>
      <input type="checkbox"> Check me out
    </label>
  </div>
  <button type="submit" class="btn btn-default">Submit</button>
</form>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-inverse">
  <div class="container">
    <div class="navbar-header">
      <%= link_to 'Simple Uploader', root_path, class: 'navbar-brand' %>
    </div>
    <div id="navbar" class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <li><%= link_to 'Photos', root_path %></li>
        <li><%= link_to 'Upload Your Photo', new_photo_path %></li>
      </ul>
    </div>
  </div>
</nav>

<div class="container">
  <% flash.each do |key, value| %>
    <div class="alert alert-<%= key %>">
      <%= value %>
    </div>
  <% end %>

  <%= yield %>
</div>

app/views/layouts/_pricelist.html.erb
<h2>Price List</h2>
<table class="table table-condensed">
	<thead>
		<tr></tr>
	</thead>
	<tbody>
		<tr>
			<td>Shellac</td>
			<td>$15</td>
		</tr>
		<tr>
			<td>Fill</td>
			<td>$24</td>
		</tr>
		<tr>
			<td>Full Set</td>
			<td>$35</td>
		</tr>
		<tr>
			<td>Back Fill</td>
			<td>$38</td>
		</tr>
		<tr>
			<td>Manicure</td>
			<td>$15</td>
		</tr>
		<tr>
			<td>Pedicure</td>
			<td>$30</td>
		</tr>		    						
		<tr>
			<td>Toe Nails Clip</td>
			<td>$12</td>
		</tr>
		<tr>
			<td>Nails Clip</td>
			<td>$7</td>
		</tr>
		<tr>
			<td>Soak Off</td>
			<td>$12</td>
		</tr>
	</tbody>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
	<head>
	  <title><%= full_title(yield(:title)) %></title>
		<meta charset="utf-8">
		<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
		<link rel="stylesheet" type="text/css" href="application.css.scss">
		<link rel="stylesheet" type="text/css" href="static_pages.css.scss">
		<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">

		<!-- 		Latest compiled and minified CSS-->		
		<link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css">
		<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">
  	<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
  	<script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>
  	<script src="http://ajax.googleapis.com/ajax/libs/angularjs/1.3.15/angular.min.js"></script>
  	<script src="nails.js"></script>
	  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
	  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
	  <%= csrf_meta_tags %>
	</head>
	<body>
		<%= yield %>
		<!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
    <script src="../../dist/js/bootstrap.min.js"></script>
    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <script src="../../assets/js/ie10-viewport-bug-workaround.js"></script>
	</body>
</html>

app/views/photos/_photo.html.erb
<div class="media">
	<div class="media-left">
		<%= link_to image_tag(photo.image.url, class: 'media-object'), photo.image.url, target: '_blank' %>
	</div>
	<div class="media-body">
		<h4 class="media-heading"><%= photo.title %></h4>
	</div>
</div>

app/views/photos/index.html.erb
<div class="page-header"><h1>Photos</h1></div>

<%= render @photos %>

app/views/photos/new.html.erb
<div class="page-header"><h1>Upload Photo</h1></div>

<%= form_for @photo do |p| %>
	<%= render 'shared/errors', object: @photo %>

	<div class="form-group">
		<%= p.label :title %>
		<%= p.text_field :title, class: 'form-control' %>
	</div>

	<div class="form-group">
		<%= p.label :image %>
		<%= p.file_field :image, class: 'form-control' %>
	</div>

	<%= p.submit 'Upload', class: 'btn btn-primary' %>
<% end %>

app/views/shared/_errors.html.erb
<% if object.errors.any? %>
  <div class="panel panel-warning errors">
    <div class="panel-heading">
      <h5><i class="glyphicon glyphicon-exclamation-sign"></i> Found errors while saving</h5>
    </div>

    <ul class="panel-body">
      <% object.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/static_pages/about.html.erb
<% provide(:title, "About") %>
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title) %> | Nancy's Nails and Hair</title>
  </head>
  <body>
		<h1>About</h1>
		<p>
		  Nancy Nga Dang founded her salon in 2001. She was well taught, training in Southern California by one of the busiest salons. She goes by the quality than the quantity.
		</p>
  </body>
</html>

app/views/static_pages/contact.html.erb
<% provide(:title, "Contact") %>
<!DOCTYPE html>
<html>
	<head>
		<title><%= yield(:title) %> | Nancy's Nails and Hair</title>
	</head>
	<body>
		<h1>Contact</h1>
		<p>
			For appointments, please call (801) 268-6366. <br>
			Walk-ins welcome! <br>
		</p>
	</body>
</html>

app/views/static_pages/help.html.erb
<% provide(:title, "Help") %>
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title) %> | Nancy's Nails and Hair</title>
  </head>
  <body>
    <h1>Help</h1>
    <p>
    	This is the help section of Nancy's Nails and Hair. A place that consists of job hiring, concerns, and everything related to a help section.
    </p>
  </body>
</html>

app/views/static_pages/home.html.erb
<% provide(:title, "Home") %>
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title) %> | Nancy's Nails & Hair</title>
  </head>
  <body ng-app="Nancys" ng-controller= "NailCtrl">
  	<div class="jumbotron"> 
  		<div class="container">
  			<div class="page-header">
  				<div class="row">
  					<div class="col-xs-12">
							<h1>Nancy's Nails & Hair 
								<small>
									<p>Providing premium, quality service since 2001.</p>      
								</small>
							</h1>
	  				</div>
	  			</div>
  			</div>
  		</div>
  	</div>
		<div class="container">
			<div class="row">
				<div class="col-sm-4">
					<span class="glyphicon glyphicon-heart-empty"></span>
					<h3>About Nancy</h3>
					<p>Nancy is prideful in her work and technique. Thoroughly trained in Southern California (US Nails), she provides beautiful, long lasting nails and happy clients!</p>		
				</div>
				<div class="col-sm-4">
					<span class="glyphicon glyphicon-phone-alt"></span>
					<h3>Schedule an Appointment</h3>
					<address>
  					<strong>Nancy's Nails & Hair</strong><br>
  					4700 S 900 E STE 11<br>
  					(Ivy Place)<br>
  					Salt Lake City, UT 84117-4980<br>
  					(801) 268-6366
					</address>
					<p>
						Open Tuesday thru Saturday<br>
						9:00 AM - 6:00 PM
					</p>
				</div>
				<div class="col-sm-4">
					<!-- Small modal -->
					<button type="button" class="btn btn-primary" data-toggle="modal" data-target=".JobForm">
						<span class="fa fa-angellist"></span>
					</button>
					<h3>Jobs</h3>
					<p>Booth rent available for hair stylist and nail technician! Call Nancy for more details.</p>
					<div class="modal fade JobForm" tabindex="-1" role="dialog" aria-labelledby="mySmallModalForm" aria-hidden="true">
						<div class="modal-dialog modal-sm">
							<div class="modal-content">
								<%= render 'layouts/jobform' %>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
		<div class="container">
			<div class="row">
				<div class="col-sm-4">
					<span class="glyphicon glyphicon-tint"></span>
					<h3>Quality Polish</h3>
					<p>See all of Nancy's latest creations, uploaded herself. (coming soon)</p>
					<%= render 'layouts/navbar' %>
				</div>
				<div class="col-sm-4">
					<!-- Small modal -->
					<button type="button" class="btn btn-primary" data-toggle="modal" data-target=".PriceList">
						<span class="fa fa-list-alt"></span>
					</button>
					<h3>Nail Services</h3>
					<div class="modal fade PriceList" tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel" aria-hidden="true">
		  			<div class="modal-dialog modal-sm">
		    			<div class="modal-content">
		    				<%= render 'layouts/pricelist' %>
		    			</div>
		  			</div>
					</div>
				</div>
				<div class="col-sm-4">
					<span class="mega-octicon octicon-beer"></span>
					<h3>Thirsty?</h3> 
					<p>Show off your nails at nearby local bars and clubs!</p>
					<ul style="list-style-type:none">
						<li>
							<a href="http://www.theroyalslc.com">The Royal</a>
						</li>
						<li>The Leprechaun Inn</li>
					</ul>
				</div>
			</div>
		</div>
		<div class="container">
			<div class="row-sm-12">
				<h1>Reviews</h1>
				<span>Post your review:</span>
				<input type="text" ng-model="user.name" />
				<p>Your review: {{user.name}}</p>
				<div ng-repeat="post in posts | orderBy:'-upvotes'">
      		<span class="glyphicon glyphicon-thumbs-up" ng-click="incrementUpvotes(post)"></span>
      		{{post.upvotes}}
      		<span style="font-size:20px; margin-left:10px;">
        		<a ng-show="post.link" href="{{post.link}}">
          		{{post.title}}
        		</a>
        		<span ng-hide="post.link">
		          {{post.title}}
		        </span>
      		</span>
      	</div>
				<form ng-submit="addPost()">
					<input type="text" ng-model="title"></input>
					<button type="submit">Post</button>
				</form>
			</div> <!-- closing row-sm-12 -->
		</div> <!-- closing container -->
		<div class="footer">
			<div class="container">
				<p>Nancy's Nails & Hair © 2015</p>
			</div>
		</div> <!-- footer -->
  </body>
</html>